# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches:
      - '**' # Запускаем для pull request'ов в любую ветку
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      working-directory:  ./src/multiplatform
      run: dotnet restore

    - name: Build project
      working-directory:  ./src/multiplatform
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      working-directory:  ./src/multiplatform
      run: dotnet test --no-restore --verbosity normal
      
 